baseURL: https://minetaro12.github.io/hugo-simple-dark/
languageCode: ja-jp
title: SimpleDark
theme: hugo-simple-dark
copyright: "&copy; 2022 yourname"
canonifyurls: true

menu:
  header:
    - name: Posts
      weight: 1
      url: /posts

    - name: Tags
      weight: 2
      url: /tags

    - name: Archives
      weight: 3
      url: /archives

    - name: MyGithub
      weight: 4
      url: https://github.com/minetaro12
      params:
        newtab: true

params:
  description: Hugo SimpleDark Theme
  image: img/ogp.jpg